config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  get '/add', to: 'pages#new'

  # routes for nested pages
  get '/*slug/add', to: 'pages#new', as: :new_subpage
  get '/*slug/edit', to: 'pages#edit', as: :edit_subpage
  get '/*slug', to: 'pages#show', as: :subpage
  patch '/*slug', to: 'pages#update'
  put '/*slug', to: 'pages#update'
  delete '/*slug', to: 'pages#destroy'

  # routes for root pages
  resources :pages, path: "", path_names: { new: 'add' }, except: [:update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
  # connecting the library to use names instead of id + adding a slug field
  extend FriendlyId
  friendly_id :name, use: :slugged

  # add parent ancestry field to Page for nested pages
  has_ancestry

  validates :title, :body, presence: true

  validates :name,  uniqueness: true,
                    presence: true,
                    format: { with: /[\wА-Яа-я]/ }

  after_save :update_descendants_slugs

  # gem Friendli_id method,
  # create transliteration, if the name is entered in Russian, and add parent slug
  def normalize_friendly_id(name)
    name_as_slug = name.to_s.to_slug.normalize(transliterations: :russian).to_s
    add_parent_slug(name_as_slug)
  end

  # gem Friendli_id method, updates slug
  def should_generate_new_friendly_id?
    name_changed?
  end

  private

  # if the page has nested pages, then update slugs of all descendants
  def update_descendants_slugs
    if has_children?
      descendants.each do |child|
        child.slug = [child.parent.slug, child.slug.split('/').last].join('/')
        child.save!
      end
    end
  end

  def add_parent_slug(name_as_slug)
    if has_parent?
      slug = [parent.slug, name_as_slug].join('/')
    else
      slug = name_as_slug
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_question, only: %i[show edit update destroy]

  def index
    @pages = Page.all
  end

  def show; end

  def new
    @page = Page.new(parent_id: params[:parent_id])
  end

  def create
    @page = Page.new(page_params)

    if @page.save
      redirect_to subpage_path(@page)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @page.update(page_params)
      redirect_to subpage_path(@page)
    else
      render :edit
    end
  end

  def destroy
    @page.destroy
    redirect_to pages_path
  end

  private

  def set_question
    @page = Page.friendly.find(params[:slug])
  end

  def page_params
    params.require(:page).permit(:name, :title, :body, :parent_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  # creating pages tree hierarchy with links
  def show_tree(page)
    tree = "<li>#{link_to page.name, subpage_path(page)}</li>"
    if page.has_children?
      tree += "<ul>"
      page.children.each do |page|
        tree += "#{show_tree(page)}"
      end
      tree += "</ul>"
    end
    tree.html_safe
  end

  # converting markdown to html
  def markdown(page)
    html_code = page.body
    # **[string]** => <b>[string]<?b>
    html_code.gsub!(/\*\*(?<bold>.*)\*\*/, '<b>\k<bold></b>')
    # //[string]// =>  <i>[string]</i>
    html_code.gsub!(/\\\\(?<ital>.*)\\\\/, '<i>\k<ital></i>')
    # ((name1/name2/name3 [string])) => <a href="[site]name1/name2/name3">[string]</a>
    html_code.gsub!(/\(\((?<link>.*) (?<name>.*)\)\)/, '<a href="/\k<link>">\k<name></a>') # ((name1/name2/name3 [string])) => name1/name2/name3 string

    html_code.html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimplePages</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.slim
= form_with model: @page, local: true do |f|
  = render 'shared/errors', resource: @page
  = f.hidden_field :parent_id

  p
    = f.label :name
  = f.text_field :name

  p
    = f.label :title
  = f.text_field :title

  p
    = f.label :body
  = f.text_area :body, size: '70x10'

  p
    = f.submit

app/views/pages/edit.html.slim
h1 Update
= render 'form'

= link_to 'Back', subpage_path(@page)

app/views/pages/index.html.slim
h1 Pages list

- @pages.roots.each do |page|
  = show_tree(page)

p
  = link_to 'New page', new_page_path

app/views/pages/new.html.slim
h1 New
= render 'form'

= link_to 'Back', root_path

app/views/pages/show.html.slim
= show_tree(@page) if @page.has_children?

p
  = @page.title

p
  = markdown(@page)

br
=link_to 'Add subpage', new_subpage_path(parent_id: @page.id)

br
= link_to 'Update', edit_subpage_path(@page)

br
  = link_to 'Delete', page_path(@page),
  method: :delete,
  data: { confirm: 'Are you sure?' }

br
= link_to 'All pages', pages_path

app/views/shared/_errors.html.slim
-if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message